# Generated by Django 4.2.7 on 2026-02-14 23:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Khatma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(unique=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-number"],
            },
        ),
        migrations.CreateModel(
            name="TasbeehCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phrase", models.CharField(max_length=120, unique=True)),
                ("count", models.PositiveBigIntegerField(default=0)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Juz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "juz_number",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(30),
                        ]
                    ),
                ),
                (
                    "reserved_by",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("reserved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "khatma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ajzaa",
                        to="charity.khatma",
                    ),
                ),
            ],
            options={
                "ordering": ["juz_number"],
            },
        ),
        migrations.AddConstraint(
            model_name="juz",
            constraint=models.UniqueConstraint(
                fields=("khatma", "juz_number"), name="unique_juz_per_khatma"
            ),
        ),
        migrations.AddConstraint(
            model_name="juz",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("reserved_at__isnull", True), ("reserved_by__isnull", True)
                    ),
                    models.Q(
                        ("reserved_at__isnull", False), ("reserved_by__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="juz_reservation_consistency",
            ),
        ),
    ]
