# Generated by Django 4.2.7 on 2026-02-16 22:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("charity", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DuaMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "content",
                    models.TextField(
                        validators=[django.core.validators.MaxLengthValidator(500)]
                    ),
                ),
                ("is_approved", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ParticipantProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("reservations_count", models.PositiveIntegerField(default=0)),
                ("completions_count", models.PositiveIntegerField(default=0)),
                ("tasbeeh_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddField(
            model_name="juz",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="juz",
            name="completed_by",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="juz",
            name="reservation_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="ActivityEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("reserve", "حجز"),
                            ("complete", "إنجاز"),
                            ("tasbeeh", "تسبيح"),
                            ("dua", "دعاء"),
                            ("expire", "انتهاء حجز"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.CharField(max_length=255)),
                (
                    "actor_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("khatma_number", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "juz_number",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(30),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="charity_act_created_a14ce4_idx"
                    ),
                    models.Index(
                        fields=["event_type", "-created_at"],
                        name="charity_act_event_t_75e03f_idx",
                    ),
                ],
            },
        ),
    ]
