# Generated by Django 4.2.7 on 2026-02-19 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("charity", "0002_duamessage_participantprogress_juz_completed_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("code", models.CharField(max_length=12, unique=True)),
                ("target_points", models.PositiveIntegerField(default=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="participantprogress",
            name="best_streak_days",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="participantprogress",
            name="dua_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="participantprogress",
            name="last_activity_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="participantprogress",
            name="referral_code",
            field=models.CharField(
                blank=True, default=None, max_length=16, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="participantprogress",
            name="referred_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invited_participants",
                to="charity.participantprogress",
            ),
        ),
        migrations.AddField(
            model_name="participantprogress",
            name="streak_days",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="activityevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("reserve", "حجز"),
                    ("complete", "إنجاز"),
                    ("tasbeeh", "تسبيح"),
                    ("dua", "دعاء"),
                    ("expire", "انتهاء حجز"),
                    ("invite", "دعوة"),
                    ("team", "فريق"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="TeamMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_memberships",
                        to="charity.participantprogress",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="charity.teamgroup",
                    ),
                ),
            ],
            options={
                "ordering": ["joined_at"],
            },
        ),
        migrations.AddField(
            model_name="teamgroup",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_teams",
                to="charity.participantprogress",
            ),
        ),
        migrations.CreateModel(
            name="ReferralAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("reserve", "حجز"),
                            ("complete", "إنجاز"),
                            ("tasbeeh", "تسبيح"),
                            ("dua", "دعاء"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invited",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invited_actions",
                        to="charity.participantprogress",
                    ),
                ),
                (
                    "inviter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_actions",
                        to="charity.participantprogress",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="teammembership",
            constraint=models.UniqueConstraint(
                fields=("team", "participant"), name="unique_team_member"
            ),
        ),
        migrations.AddConstraint(
            model_name="teammembership",
            constraint=models.UniqueConstraint(
                fields=("participant",), name="one_team_per_participant"
            ),
        ),
        migrations.AddIndex(
            model_name="teamgroup",
            index=models.Index(
                fields=["-created_at"], name="charity_tea_created_ba45fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="referralaction",
            index=models.Index(
                fields=["inviter", "-created_at"], name="charity_ref_inviter_8a079f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="referralaction",
            index=models.Index(
                fields=["action_type", "-created_at"],
                name="charity_ref_action__1982e4_idx",
            ),
        ),
    ]
